spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 1qaz@WSX
  redis:
    port: 6379
    host: 127.0.0.1
  session:
    timeout: 10
    
server:
  port: 8080
  

istimeless:
  security:
    social:
      filterProcessesUrl: /socialLogin
      qq:
        app-id: 123
        app-secret: 456
        providerId: qq
    browser:
#      loginPage: /demologin.html
      loginType: JSON
#    code:
#      image:
#        length: 6
#        width: 30
#        url: /user,/user/*


security:
  oauth2:
    client:
      client-id: istimeless
      client-secret: istimelesssecret
